pipeline:
  name: sample_one
  identifier: sample_one
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: cds
        identifier: cds
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8new
          execution:
            steps:
              - stepGroup:
                  name: und
                  identifier: und
                  steps:
                    - step:
                        type: GitClone
                        name: GitClone_1
                        identifier: GitClone_1
                        spec:
                          connectorRef: account.AbhinandanGit
                          repoName: " BasicMEAN"
                          cloneDirectory: /harness/gitpath
                          build:
                            type: branch
                            spec:
                              branch: main
                    - step:
                        type: Run
                        name: Run_1
                        identifier: Run_1
                        spec:
                          connectorRef: DockerConnector
                          image: nginx
                          shell: Sh
                          command: echo "hello"
                  stepGroupInfra:
                    type: KubernetesDirect
                    spec:
                      connectorRef: account.second
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: ECS_INFRA
            environmentInputs:
              variables:
                - name: dbname
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: two
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: chhbc
        identifier: chhbc
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo "hey"
                          echo <+pipeline.stages.cds.status>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: nn
        identifier: nn
        description: ""
        type: Deployment
        spec:
          deploymentType: Asg
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: ASG
            serviceInputs:
              serviceDefinition:
                type: Asg
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: ECS_INFRA
            environmentInputs:
              variables:
                - name: dbname
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: asg
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  allowStageExecutions: true
