pipeline:
  name: sample_one
  identifier: sample_one
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags: {}
  stages:
    - stage:
        name: cds
        identifier: cds
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8new
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
          environment:
            environmentRef: ECS_INFRA
            environmentInputs:
              variables:
                - name: dbname
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: two
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: chhbc
        identifier: chhbc
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: echo "hey"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  allowStageExecutions: true
